repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: \.txt$
  - id: trailing-whitespace                # Remove trailing whitespaces
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: detect-private-key
  - id: sort-simple-yaml
        # Fix common spelling mistakes
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    args: [--ignore-words-list=alos, --ignore-regex=\bnin\b]
    types_or: [python, rst, markdown]
    files: ^(geoutils|doc|tests)/

        # Replace relative imports (e.g. 'from . import georaster' -> 'from geoutils import georaster')
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  - id: absolufy-imports

        # Format the code aggressively using black
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args: [--line-length=120]

        # Lint the code using flake8
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [--max-line-length=120, --extend-ignore=E203]
    additional_dependencies:
    - flake8-comprehensions==3.10.1
    - flake8-bugbear==22.10.27
    files: ^(geoutils|tests)
        # Lint the code using mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    args: [--strict, --ignore-missing-imports, --allow-untyped-calls, --show-error-codes, --no-warn-unused-ignores, --disable-error-code=attr-defined, --disable-error-code=name-defined] # "Name 'XXX' is not defined" occurs because of the pre-commit env.


    additional_dependencies: [tokenize-rt==5.0.0]



        # Sort imports using isort
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [--profile, black]

  # Automatically upgrade syntax to a minimum version
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.3
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

        # Various formattings
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
                # Single backticks should apparently not be used
  - id: rst-backticks
                # Check that all directives end with double colon
  - id: rst-directive-colons
    types: [text]
    types_or: [python, rst]
                # Inline code should not touch normal text
  - id: rst-inline-touching-normal
    types: [text]
    types_or: [python, rst]
                # Eval should never be used (can do arbitrary code execution)
  - id: python-no-eval
                # Enforce the use of type annotations instead of docstring type comments
  - id: python-use-type-annotations

        # Add custom regex lints (see .relint.yml)
- repo: https://github.com/codingjoe/relint
  rev: 2.1.1
  hooks:
  - id: relint

- repo: https://github.com/lovesegfault/beautysh
  rev: 776863dc573a37518fbca2d61878bfbd787245ab
  hooks:
  - id: beautysh

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: 3c4addcc0aa9a6eb9fb64d9206733110d1153a52
  hooks:
  - id: nixpkgs-fmt
